apiVersion: v1
kind: Namespace
metadata:
  name: eviction-006-minavailable3-fast
---
apiVersion: workload.serving.volcano.sh/v1alpha1
kind: ModelServing
metadata:
  name: evict-sg-minavailable3-fast
  namespace: eviction-006-minavailable3-fast
spec:
  replicas: 3
  schedulerName: volcano
  rolloutStrategy:
    evictionStrategy:
      protectionLevel: ServingGroup
      minAvailable: 3
  template:
    roles:
    - name: prefill
      replicas: 1
      workerReplicas: 0
      entryTemplate:
        spec:
          nodeSelector:
            kubernetes.io/hostname: kind-worker
          containers:
          - name: main
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ["sh", "-c", "sleep 3600"]
    - name: decode
      replicas: 1
      workerReplicas: 0
      entryTemplate:
        spec:
          nodeSelector:
            kubernetes.io/hostname: kind-worker
          containers:
          - name: main
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ["sh", "-c", "sleep 3600"]
