apiVersion: v1
kind: Namespace
metadata:
  name: eviction-009-role-currentready
---
apiVersion: workload.serving.volcano.sh/v1alpha1
kind: ModelServing
metadata:
  name: evict-role-currentready
  namespace: eviction-009-role-currentready
spec:
  replicas: 1
  schedulerName: volcano
  rolloutStrategy:
    evictionStrategy:
      protectionLevel: Role
      roleMinAvailable:
        decode: 2
  template:
    roles:
    - name: decode
      replicas: 3
      workerReplicas: 0
      entryTemplate:
        spec:
          containers:
          - name: main
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ["sh", "-c", "sleep 3600"]

