apiVersion: workload.serving.volcano.sh/v1alpha1
kind: ModelServing
metadata:
  name: evict-sg
  namespace: eviction-006
spec:
  replicas: 3
  schedulerName: volcano
  rolloutStrategy:
    evictionStrategy:
      protectionLevel: ServingGroup
      minAvailable: 2
  template:
    roles:
    - name: worker
      replicas: 1
      workerReplicas: 0
      entryTemplate:
        spec:
          containers:
          - name: main
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ["sh", "-c", "sleep 3600"]
