apiVersion: workload.serving.volcano.sh/v1alpha1
kind: ModelServing
metadata:
  name: evict-validation-sg-valid
spec:
  replicas: 3
  schedulerName: volcano
  rolloutStrategy:
    type: ServingGroupRollingUpdate
    evictionStrategy:
      protectionLevel: ServingGroup
      minAvailable: 2
  template:
    roles:
    - name: decode
      replicas: 1
      entryTemplate:
        spec:
          containers:
          - name: decode
            image: nginx:1.25
      workerReplicas: 0
